### ISSUE TITLE
How to replace interfaces with concrete implementations?

### ISSUE THREAD

**Issue by hassankhan** [ukautz/wart#2]
For example, when using Twig, the `Twig_Environment` object requires another object of type `Twig_LoaderInterface`. Can I somehow "map" an object onto it? Using createArgs() doesn't seem to be working for me.

**Comment by meetmatt** [comment]
One solution: configurable aliases, like in symfony dependency injection component:
[
  
  'aliases' => [
    Twig_LoaderInterface::class => Twig_Loader_Filesystem::class,
  ]
];

**Comment by meetmatt** [comment]
It could be a useful feature, already actively using it in my own home project, saves time and allows to auto-wire interfaces, e.g.:

``` php
$container = new Wart([], [
    'createArgs' => [
        Twig_Loader_Filesystem::class => [__DIR__ . '/templates'],
        Twig_Environment::class => [['cache' => __DIR__ . '/cache']],
    ],
    'aliases' => [
        Twig_LoaderInterface::class => Twig_Loader_Filesystem::class
    ],
]);

$twig = $container[Twig_Environment::class]; // works correctly
```

**Comment by meetmatt** [comment]
Added here: https://github.com/ukautz/wart/pull/4

**Comment by meetmatt** [comment]
@ukautz you can close this issue I guess
